services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nightlife
      POSTGRES_PASSWORD: nightlife
      POSTGRES_DB: nightlife
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
