import type { AnalyticsSummary } from "@/lib/types";

export const mockAnalytics: AnalyticsSummary = {
  revenueTonight: 12420,
  revenueDeltaPct: 12.4,
  ordersTonight: 143,
  ordersDeltaPct: 8.1,
  avgOrderValue: 86.9,
  avgOrderDeltaPct: 3.7,
  activeTables: 9,
  totalTables: 23,
  avgFulfillmentMinutes: 7.2,
  orderEta: { avgAcceptMinutes: 1.4, avgPrepMinutes: 5.8, avgTotalMinutes: 7.2 },
  topItems: [
    { name: "Ace of Spades Brut Gold", count: 7, revenue: 3500, categoryId: "cat-champagne" },
    { name: "Belvedere Pure 1.75L", count: 11, revenue: 3300, categoryId: "cat-vodka" },
    { name: "Dom Pérignon Vintage", count: 8, revenue: 2560, categoryId: "cat-champagne" },
    { name: "Don Julio 1942", count: 6, revenue: 2040, categoryId: "cat-tequila" },
    { name: "Mr Ace (package)", count: 1, revenue: 2400 },
  ],
  // Hour and zone splits must each sum to revenueTonight — they render beside it.
  revenueByHour: [
    { label: "22:00", revenue: 840, orders: 14 },
    { label: "23:00", revenue: 1580, orders: 22 },
    { label: "00:00", revenue: 2420, orders: 29 },
    { label: "01:00", revenue: 2900, orders: 31 },
    { label: "02:00", revenue: 2610, orders: 26 },
    { label: "03:00", revenue: 1510, orders: 15 },
    { label: "04:00", revenue: 560, orders: 6 },
  ],
  revenueByDay: [
    { label: "Thu", revenue: 6600, orders: 96 },
    { label: "Fri", revenue: 11000, orders: 138 },
    { label: "Sat", revenue: 14300, orders: 171 },
    { label: "Sun", revenue: 2800, orders: 42 },
    { label: "Thu", revenue: 7300, orders: 104 },
    { label: "Fri", revenue: 11900, orders: 149 },
    { label: "Sat", revenue: 12420, orders: 143 },
  ],
  staffPerformance: [
    { staffId: "st-sofia", name: "Sofia Lévesque", role: "bartender", ordersDelivered: 34, avgDeliveryMinutes: 6.9, revenueServed: 2900, avgAcceptMinutes: 0.9, ordersPerShiftHour: 4.9 },
    { staffId: "st-theo", name: "Théo Tremblay", role: "bartender", ordersDelivered: 26, avgDeliveryMinutes: 8.4, revenueServed: 1700, avgAcceptMinutes: 2.1, ordersPerShiftHour: 3.7 },
    { staffId: "st-lucas", name: "Lucas Gagné", role: "host", ordersDelivered: 16, avgDeliveryMinutes: 7.4, revenueServed: 400, avgAcceptMinutes: 1.5, ordersPerShiftHour: 2.3 },
    { staffId: "st-nina", name: "Nina Côté", role: "runner", ordersDelivered: 0, avgDeliveryMinutes: 0, revenueServed: 0, helpResolved: 5, avgHelpMinutes: 2.8 },
    { staffId: "st-karim", name: "Karim Ouellet", role: "runner", ordersDelivered: 0, avgDeliveryMinutes: 0, revenueServed: 0, helpResolved: 3, avgHelpMinutes: 3.4 },
  ],
  categoryDepletion: [
    { categoryId: "cat-champagne", categoryName: "Champagne", unitsSold: 21, unitsInStock: 34, sellThrough: 0.38, soldOutMinutes: 0, restockUnits: 12, deadItem: false },
    { categoryId: "cat-vodka", categoryName: "Vodka", unitsSold: 17, unitsInStock: 22, sellThrough: 0.44, soldOutMinutes: 0, restockUnits: 10, deadItem: false },
    { categoryId: "cat-tequila", categoryName: "Tequila", unitsSold: 12, unitsInStock: 9, sellThrough: 0.57, soldOutMinutes: 45, restockUnits: 8, deadItem: false },
    { categoryId: "cat-cognac", categoryName: "Cognac", unitsSold: 6, unitsInStock: 14, sellThrough: 0.3, soldOutMinutes: 0, restockUnits: 0, deadItem: false },
    { categoryId: "cat-whisky", categoryName: "Whisky", unitsSold: 5, unitsInStock: 18, sellThrough: 0.22, soldOutMinutes: 0, restockUnits: 0, deadItem: false },
    { categoryId: "cat-washers", categoryName: "Washers", unitsSold: 43, unitsInStock: 61, sellThrough: 0.41, soldOutMinutes: 0, restockUnits: 24, deadItem: false },
  ],
  revenueByZone: [
    { zoneId: "zone-vip", zoneName: "VIP Mezzanine", revenue: 7500 },
    { zoneId: "zone-dance", zoneName: "Main Floor", revenue: 2560 },
    { zoneId: "zone-terrace", zoneName: "Terrace", revenue: 1500 },
    { zoneId: "zone-bar", zoneName: "Back Bar", revenue: 860 },
  ],
  sessions: {
    totalSessions: 31,
    approvalRate: 0.87,
    denialRate: 0.13,
    avgApprovalMinutes: 2.4,
    avgDurationMinutes: 142,
    avgPartySize: 3.2,
    revenuePerSession: 400.65,
    revenuePerGuest: 125.2,
    settlementMix: [
      { method: "terminal", count: 19, pct: 0.61 },
      { method: "cash", count: 8, pct: 0.26 },
      { method: "house", count: 4, pct: 0.13 },
    ],
    avgClosureMinutes: 4.8,
  },
  reservations: {
    requested: 18,
    confirmed: 14,
    seated: 12,
    completed: 11,
    cancelled: 3,
    confirmRate: 0.78,
    seatedRate: 0.86,
    // Denominators: confirmRate & cancellationRate over requested; seatedRate & noShowRate over confirmed.
    cancellationRate: 0.17,
    noShowRate: 0.14,
    avgLeadDays: 3.2,
    totalCovers: 44,
    sourceSplit: [
      { source: "manager", count: 11, pct: 0.61 },
      { source: "public", count: 7, pct: 0.39 },
    ],
    channelSplit: [
      { channel: "manager", count: 11, pct: 0.61 },
      { channel: "embed", count: 4, pct: 0.22 },
      { channel: "direct", count: 2, pct: 0.11 },
      { channel: "walk-in", count: 1, pct: 0.06 },
    ],
    partySizeDistribution: [
      { size: 2, count: 5 },
      { size: 4, count: 7 },
      { size: 6, count: 4 },
      { size: 8, count: 2 },
    ],
  },
  happyHours: {
    rules: [
      { ruleId: "hh-1", ruleName: "Early Bird", orders: 22, revenue: 1340, discountGiven: 268, categoryUpliftPct: 0.35 },
      { ruleId: "hh-2", ruleName: "Last Call", orders: 14, revenue: 780, discountGiven: 156, categoryUpliftPct: 0.18 },
    ],
    totalDiscountGiven: 424,
    totalHhOrders: 36,
    totalHhRevenue: 2120,
  },
  events: {
    events: [
      { eventId: "evt-1", eventName: "Latin Night", invited: 80, confirmed: 62, checkedIn: 48, capacityUtilization: 0.8, guestlistConversion: 0.6, eventRevenue: 5200, avgWeekdayRevenue: 3800 },
      { eventId: "evt-2", eventName: "DJ Sora", invited: 120, confirmed: 95, checkedIn: 82, capacityUtilization: 0.91, guestlistConversion: 0.68, eventRevenue: 8400, avgWeekdayRevenue: 4200 },
    ],
    totalEvents: 2,
    avgCapacityUtilization: 0.86,
  },
  promotions: {
    promotions: [
      { promotionId: "promo-1", code: "WELCOME10", redemptions: 8, discountCost: 69.52, attributedRevenue: 695.2, aovWithPromo: 86.9, aovWithoutPromo: 92.4 },
      { promotionId: "promo-2", code: "VIP25", redemptions: 3, discountCost: 112.5, attributedRevenue: 450, aovWithPromo: 150, aovWithoutPromo: 92.4 },
    ],
    totalRedemptions: 11,
    totalDiscountCost: 182.02,
  },
  orderFunnel: {
    placed: 143,
    accepted: 138,
    preparing: 0,
    delivered: 132,
    cancelled: 5,
    cancellationRate: 0.035,
    tipRate: 0.62,
    avgTip: 8.4,
    serviceFeeRevenue: 428.4,
    giftOrders: 4,
    giftRevenue: 1120,
    modifierAttachRate: 0.28,
  },
  inventoryDepth: {
    soldOutEventsPerNight: 1,
    totalSoldOutMinutes: 45,
    restockSaleRatio: 0.52,
    deadItems: 0,
  },
};
