import type { AnalyticsSummary } from "@/lib/types";

export const mockAnalytics: AnalyticsSummary = {
  revenueTonight: 12420,
  revenueDeltaPct: 12.4,
  ordersTonight: 143,
  ordersDeltaPct: 8.1,
  avgOrderValue: 86.9,
  avgOrderDeltaPct: 3.7,
  activeTables: 9,
  totalTables: 23,
  avgFulfillmentMinutes: 7.2,
  topItems: [
    { name: "Ace of Spades Brut Gold", count: 7, revenue: 3500, categoryId: "cat-champagne" },
    { name: "Belvedere Pure 1.75L", count: 11, revenue: 3300, categoryId: "cat-vodka" },
    { name: "Dom Pérignon Vintage", count: 8, revenue: 2560, categoryId: "cat-champagne" },
    { name: "Don Julio 1942", count: 6, revenue: 2040, categoryId: "cat-tequila" },
    { name: "Mr Ace (package)", count: 1, revenue: 2400 },
  ],
  revenueByHour: [
    { label: "22:00", revenue: 840, orders: 14 },
    { label: "23:00", revenue: 1580, orders: 22 },
    { label: "00:00", revenue: 2420, orders: 29 },
    { label: "01:00", revenue: 2800, orders: 31 },
    { label: "02:00", revenue: 2610, orders: 26 },
    { label: "03:00", revenue: 1510, orders: 15 },
    { label: "04:00", revenue: 560, orders: 6 },
  ],
  revenueByDay: [
    { label: "Thu", revenue: 6600, orders: 96 },
    { label: "Fri", revenue: 11000, orders: 138 },
    { label: "Sat", revenue: 14300, orders: 171 },
    { label: "Sun", revenue: 2800, orders: 42 },
    { label: "Thu", revenue: 7300, orders: 104 },
    { label: "Fri", revenue: 11900, orders: 149 },
    { label: "Sat", revenue: 12420, orders: 143 },
  ],
  staffPerformance: [
    { staffId: "st-nina", name: "Nina Côté", role: "runner", ordersDelivered: 38, avgDeliveryMinutes: 6.1, revenueServed: 4600 },
    { staffId: "st-karim", name: "Karim Ouellet", role: "runner", ordersDelivered: 29, avgDeliveryMinutes: 7.8, revenueServed: 2800 },
    { staffId: "st-sofia", name: "Sofia Lévesque", role: "bartender", ordersDelivered: 34, avgDeliveryMinutes: 6.9, revenueServed: 2900 },
    { staffId: "st-theo", name: "Théo Tremblay", role: "bartender", ordersDelivered: 26, avgDeliveryMinutes: 8.4, revenueServed: 1700 },
    { staffId: "st-lucas", name: "Lucas Gagné", role: "host", ordersDelivered: 16, avgDeliveryMinutes: 7.4, revenueServed: 400 },
  ],
  categoryDepletion: [
    { categoryId: "cat-champagne", categoryName: "Champagne", unitsSold: 21, unitsInStock: 34 },
    { categoryId: "cat-vodka", categoryName: "Vodka", unitsSold: 17, unitsInStock: 22 },
    { categoryId: "cat-tequila", categoryName: "Tequila", unitsSold: 12, unitsInStock: 9 },
    { categoryId: "cat-cognac", categoryName: "Cognac", unitsSold: 6, unitsInStock: 14 },
    { categoryId: "cat-whisky", categoryName: "Whisky", unitsSold: 5, unitsInStock: 18 },
    { categoryId: "cat-washers", categoryName: "Washers", unitsSold: 43, unitsInStock: 61 },
  ],
  revenueByZone: [
    { zoneId: "zone-vip", zoneName: "VIP Mezzanine", revenue: 7500 },
    { zoneId: "zone-dance", zoneName: "Main Floor", revenue: 2400 },
    { zoneId: "zone-terrace", zoneName: "Terrace", revenue: 1500 },
    { zoneId: "zone-bar", zoneName: "Back Bar", revenue: 860 },
  ],
};
