import type { AnalyticsSummary } from "@/lib/types";

export const mockAnalytics: AnalyticsSummary = {
  revenueTonight: 18426,
  revenueDeltaPct: 12.4,
  ordersTonight: 143,
  ordersDeltaPct: 8.1,
  avgOrderValue: 128.9,
  avgOrderDeltaPct: 3.7,
  activeTables: 9,
  totalTables: 23,
  avgFulfillmentMinutes: 7.2,
  topItems: [
    { name: "Ace of Spades Brut Gold", count: 7, revenue: 5250, categoryId: "cat-champagne" },
    { name: "Belvedere Pure 1.75L", count: 11, revenue: 4620, categoryId: "cat-vodka" },
    { name: "Dom Pérignon Vintage", count: 8, revenue: 3840, categoryId: "cat-champagne" },
    { name: "Don Julio 1942", count: 6, revenue: 2880, categoryId: "cat-tequila" },
    { name: "Mr Ace (package)", count: 1, revenue: 3400 },
  ],
  revenueByHour: [
    { label: "22:00", revenue: 1240, orders: 14 },
    { label: "23:00", revenue: 2380, orders: 22 },
    { label: "00:00", revenue: 3620, orders: 29 },
    { label: "01:00", revenue: 4180, orders: 31 },
    { label: "02:00", revenue: 3910, orders: 26 },
    { label: "03:00", revenue: 2260, orders: 15 },
    { label: "04:00", revenue: 836, orders: 6 },
  ],
  revenueByDay: [
    { label: "Thu", revenue: 9800, orders: 96 },
    { label: "Fri", revenue: 16400, orders: 138 },
    { label: "Sat", revenue: 21300, orders: 171 },
    { label: "Sun", revenue: 4200, orders: 42 },
    { label: "Thu", revenue: 10900, orders: 104 },
    { label: "Fri", revenue: 17800, orders: 149 },
    { label: "Sat", revenue: 18426, orders: 143 },
  ],
  staffPerformance: [
    { staffId: "st-nina", name: "Nina Kovač", role: "runner", ordersDelivered: 38, avgDeliveryMinutes: 6.1, revenueServed: 6840 },
    { staffId: "st-karim", name: "Karim Haddad", role: "runner", ordersDelivered: 29, avgDeliveryMinutes: 7.8, revenueServed: 4120 },
    { staffId: "st-sofia", name: "Sofia Rossi", role: "bartender", ordersDelivered: 34, avgDeliveryMinutes: 6.9, revenueServed: 4360 },
    { staffId: "st-theo", name: "Théo Lambert", role: "bartender", ordersDelivered: 26, avgDeliveryMinutes: 8.4, revenueServed: 2510 },
    { staffId: "st-lucas", name: "Lucas Moreau", role: "host", ordersDelivered: 16, avgDeliveryMinutes: 7.4, revenueServed: 596 },
  ],
  categoryDepletion: [
    { categoryId: "cat-champagne", categoryName: "Champagne", unitsSold: 21, unitsInStock: 34 },
    { categoryId: "cat-vodka", categoryName: "Vodka", unitsSold: 17, unitsInStock: 22 },
    { categoryId: "cat-tequila", categoryName: "Tequila", unitsSold: 12, unitsInStock: 9 },
    { categoryId: "cat-cognac", categoryName: "Cognac", unitsSold: 6, unitsInStock: 14 },
    { categoryId: "cat-whisky", categoryName: "Whisky", unitsSold: 5, unitsInStock: 18 },
    { categoryId: "cat-washers", categoryName: "Washers", unitsSold: 43, unitsInStock: 61 },
  ],
  revenueByZone: [
    { zoneId: "zone-vip", zoneName: "VIP Mezzanine", revenue: 11240 },
    { zoneId: "zone-dance", zoneName: "Main Floor", revenue: 3620 },
    { zoneId: "zone-terrace", zoneName: "Terrace", revenue: 2280 },
    { zoneId: "zone-bar", zoneName: "Back Bar", revenue: 1286 },
  ],
};
