import type { EventTalent } from "@/lib/types";

export const mockEventTalent: EventTalent[] = [
  {
    id: "tal-1",
    eventId: "evt-1",
    venueId: "venue-1",
    name: "DJ Mirage",
    role: "dj",
    setTimes: [{ start: "23:00", end: "01:30" }, { start: "02:00", end: "04:00" }],
    arrivalTime: new Date(Date.now() + 3 * 86400000 + 3 * 3600000).toISOString(),
    rider: "Pioneer CDJ-3000 ×2, DJM-A9 mixer, 2× stage monitors, 6× water bottles, green room with fruit platter",
    greenRoom: "Green Room A",
    status: "scheduled",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tal-2",
    eventId: "evt-1",
    venueId: "venue-1",
    name: "MC Flow",
    role: "mc",
    setTimes: [{ start: "23:30", end: "02:00" }],
    arrivalTime: new Date(Date.now() + 3 * 86400000 + 2 * 3600000).toISOString(),
    rider: "Wireless mic (Shure ULXD), stage monitor",
    greenRoom: "Green Room A",
    status: "scheduled",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tal-3",
    eventId: "evt-3",
    venueId: "venue-1",
    name: "DJ Écho",
    role: "dj",
    setTimes: [{ start: "22:00", end: "01:00" }],
    rider: "CDJ setup, sushi platter",
    greenRoom: "Green Room B",
    status: "completed",
    createdAt: new Date().toISOString(),
  },
];
