import type { GuestLink, GuestProfile } from "@/lib/types";

const daysAgo = (d: number) => new Date(Date.now() - d * 86_400_000).toISOString();

/**
 * A night's worth of guest identity: three regulars with real history (one a
 * VIP), one banned patron the door must refuse on sight. Every profile here
 * exists because someone *gave* us identity (door ID check, reservation, or
 * a host tag) — never because a QR guest was silently fingerprinted.
 */
export const mockGuestProfiles: GuestProfile[] = [
  {
    id: "gp-felix",
    venueId: "venue-1",
    displayName: "Félix Marchand",
    firstName: "Félix",
    lastName: "Marchand",
    phone: "+15145550234",
    dobYear: 1991,
    tags: ["regular", "high-spender"],
    vipTier: "vip",
    status: "active",
    notes: "Prefers VIP-01/02, always orders Dom Pérignon or better.",
    marketingConsent: { email: true, sms: true, capturedAt: daysAgo(200), source: "door" },
    createdAt: daysAgo(200),
    lastVisitAt: daysAgo(7),
    visitCount: 12,
    lifetimeNetCents: 840_000,
  },
  {
    id: "gp-amelie",
    venueId: "venue-1",
    displayName: "Amélie Roy",
    firstName: "Amélie",
    lastName: "Roy",
    phone: "+15145550456",
    email: "amelie.roy@example.com",
    dobYear: 1996,
    tags: ["regular"],
    vipTier: "regular",
    status: "active",
    marketingConsent: { email: true, sms: false, capturedAt: daysAgo(150), source: "reservation" },
    createdAt: daysAgo(150),
    lastVisitAt: daysAgo(14),
    visitCount: 6,
    lifetimeNetCents: 210_000,
  },
  {
    id: "gp-thomas",
    venueId: "venue-1",
    displayName: "Thomas Gagnon",
    firstName: "Thomas",
    lastName: "Gagnon",
    phone: "+15145550678",
    tags: ["industry"],
    vipTier: "regular",
    status: "active",
    marketingConsent: { email: false, sms: false, capturedAt: daysAgo(90), source: "door" },
    createdAt: daysAgo(90),
    lastVisitAt: daysAgo(21),
    visitCount: 4,
    lifetimeNetCents: 96_000,
  },
  {
    id: "gp-banned-1",
    venueId: "venue-1",
    displayName: "Étienne Boivin",
    firstName: "Étienne",
    lastName: "Boivin",
    dobYear: 1998,
    tags: [],
    vipTier: "none",
    status: "banned",
    banReason: "Altercation with staff — refused re-entry a second time.",
    bannedByStaffId: "st-viktor",
    notes: "Do not admit without manager sign-off.",
    marketingConsent: { email: false, sms: false, capturedAt: daysAgo(45), source: "door" },
    createdAt: daysAgo(45),
    lastVisitAt: daysAgo(45),
    visitCount: 3,
    lifetimeNetCents: 42_000,
  },
  {
    id: "gp-sarah",
    venueId: "venue-1",
    displayName: "Sarah Delorme",
    firstName: "Sarah",
    lastName: "Delorme",
    phone: "+15145550890",
    email: "sarah.delorme@example.com",
    dobYear: 1994,
    tags: ["regular"],
    vipTier: "regular",
    status: "active",
    notes: "Prefers the terrace — always arrives with a party of 6+.",
    marketingConsent: { email: true, sms: true, capturedAt: daysAgo(120), source: "reservation" },
    createdAt: daysAgo(120),
    lastVisitAt: daysAgo(7),
    visitCount: 8,
    lifetimeNetCents: 520_000,
  },
  {
    id: "gp-antoine",
    venueId: "venue-1",
    displayName: "Antoine Moreau",
    firstName: "Antoine",
    lastName: "Moreau",
    phone: "+15145550123",
    tags: ["industry", "high-spender"],
    vipTier: "vip",
    status: "active",
    notes: "Industry regular — runs a competing venue but comes here for the terrace. Always orders by the case.",
    marketingConsent: { email: false, sms: true, capturedAt: daysAgo(180), source: "door" },
    createdAt: daysAgo(180),
    lastVisitAt: daysAgo(7),
    visitCount: 15,
    lifetimeNetCents: 1_100_000,
  },
  {
    id: "gp-camille",
    venueId: "venue-1",
    displayName: "Camille Girard",
    firstName: "Camille",
    lastName: "Girard",
    phone: "+15145550432",
    email: "camille.g@example.com",
    tags: ["birthday"],
    vipTier: "none",
    status: "active",
    marketingConsent: { email: true, sms: false, capturedAt: daysAgo(2), source: "reservation" },
    createdAt: daysAgo(2),
    visitCount: 1,
    lifetimeNetCents: 18_000,
  },
  {
    id: "gp-leo",
    venueId: "venue-1",
    displayName: "Léo Fortin",
    firstName: "Léo",
    lastName: "Fortin",
    phone: "+15145550654",
    dobYear: 1990,
    tags: ["regular", "high-spender"],
    vipTier: "vip",
    status: "active",
    notes: "Music producer — brings celebrity guests. Always tips well.",
    marketingConsent: { email: true, sms: true, capturedAt: daysAgo(300), source: "door" },
    createdAt: daysAgo(300),
    lastVisitAt: daysAgo(14),
    visitCount: 22,
    lifetimeNetCents: 2_400_000,
  },
  {
    id: "gp-mylene",
    venueId: "venue-1",
    displayName: "Mylène Richard",
    firstName: "Mylène",
    lastName: "Richard",
    email: "mylene.r@example.com",
    tags: ["allergy-noted"],
    vipTier: "none",
    status: "active",
    notes: "Severe nut allergy — flagged on menu. First visit tonight.",
    marketingConsent: { email: true, sms: false, capturedAt: daysAgo(1), source: "reservation" },
    createdAt: daysAgo(1),
    visitCount: 0,
    lifetimeNetCents: 0,
  },
];

export const mockGuestLinks: GuestLink[] = [
  { id: "gl-1", guestProfileId: "gp-felix", sessionId: "gs-1", createdAt: new Date().toISOString() },
  { id: "gl-2", guestProfileId: "gp-sarah", reservationId: "res-3", createdAt: daysAgo(7) },
  { id: "gl-3", guestProfileId: "gp-antoine", sessionId: "gs-3", createdAt: new Date().toISOString() },
];
