import type { Incident, IncidentNote } from "@/lib/types";
import { CURRENT_BUSINESS_DATE } from "./door";

const minsAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

/** Two seeded incidents so security's log and the manager's view are non-empty on first paint. */
export const mockIncidents: Incident[] = [
  {
    id: "inc-1",
    venueId: "venue-1",
    businessDate: CURRENT_BUSINESS_DATE,
    type: "altercation",
    severity: "medium",
    occurredAt: minsAgo(50),
    zoneId: "zone-dance",
    involvedStaffIds: ["st-viktor"],
    narrative: "Two guests near MF-05 exchanged words over a spilled drink; separated before it escalated.",
    actionsTaken: "Moved both parties to opposite ends of the floor, monitored for 20 minutes.",
    policeInvolved: false,
    reportedByStaffId: "st-viktor",
    reportedByStaffName: "Viktor Michaud",
    status: "resolved",
    reportable: false,
  },
  {
    id: "inc-2",
    venueId: "venue-1",
    businessDate: CURRENT_BUSINESS_DATE,
    type: "refused-entry",
    severity: "low",
    occurredAt: minsAgo(30),
    guestProfileId: "gp-banned-1",
    involvedStaffIds: ["st-marcus"],
    narrative: "Étienne Boivin attempted entry at the main door; profile matched an active ban.",
    actionsTaken: "Refused entry, informed of ban reason, no further incident.",
    policeInvolved: false,
    reportedByStaffId: "st-marcus",
    reportedByStaffName: "Marcus Fontaine",
    status: "open",
    reportable: false,
  },
  {
    id: "inc-3",
    venueId: "venue-1",
    businessDate: CURRENT_BUSINESS_DATE,
    type: "medical",
    severity: "low",
    occurredAt: minsAgo(15),
    zoneId: "zone-dance",
    involvedStaffIds: ["st-nina"],
    narrative: "Guest at MF-03 reported dizziness and nausea — likely dehydration.",
    actionsTaken: "Provided water, escorted to quieter area on terrace for fresh air. Guest recovered after 10 minutes.",
    policeInvolved: false,
    reportedByStaffId: "st-nina",
    reportedByStaffName: "Nina Côté",
    status: "resolved",
    reportable: false,
  },
  {
    id: "inc-4",
    venueId: "venue-1",
    businessDate: CURRENT_BUSINESS_DATE,
    type: "theft",
    severity: "medium",
    occurredAt: minsAgo(5),
    zoneId: "zone-vip",
    tableId: "t-vip-3",
    involvedStaffIds: ["st-viktor"],
    narrative: "Guest reported a handbag missing from VIP-03. Last seen on the booth 10 minutes prior.",
    actionsTaken: "Security swept the zone, reviewed exit footage, filed report. Guest provided contact details for follow-up.",
    policeInvolved: false,
    reportedByStaffId: "st-viktor",
    reportedByStaffName: "Viktor Michaud",
    status: "open",
    reportable: false,
  },
  {
    id: "inc-5",
    venueId: "venue-1",
    businessDate: CURRENT_BUSINESS_DATE,
    type: "ejection",
    severity: "high",
    occurredAt: minsAgo(2),
    zoneId: "zone-dance",
    involvedStaffIds: ["st-viktor", "st-marcus"],
    narrative: "Guest on MF-07 became aggressive with bartender after being refused further alcohol service. Escalated to shouting and shoving.",
    actionsTaken: "Two security removed the guest from the premises. Police notified pre-emptively as per protocol. Incident report filed.",
    policeInvolved: true,
    reportedByStaffId: "st-viktor",
    reportedByStaffName: "Viktor Michaud",
    status: "open",
    reportable: true,
    regulatoryDeadline: new Date(Date.now() + 48 * 3600_000).toISOString(),
    regulatoryAuthority: "SPVM (Service de police de la Ville de Montréal)",
  },
];

export const mockIncidentNotes: IncidentNote[] = [
  {
    id: "in-1",
    incidentId: "inc-1",
    note: "Followed up with both parties' hosts — no further issues tonight.",
    authorStaffId: "st-amara",
    authorStaffName: "Amara Bélanger",
    createdAt: minsAgo(40),
  },
];
