import type { Order, GuestSession, HelpRequest } from "@/lib/types";

const minsAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

export const mockOrders: Order[] = [
  {
    id: "ord-1",
    code: "A-038",
    venueId: "venue-1",
    tableId: "t-vip-2",
    tableCode: "VIP-02",
    zoneId: "zone-vip",
    zoneName: "VIP Mezzanine",
    guestName: "Chloé",
    items: [
      { id: "oi-1", menuItemId: "mi-dom", name: "Dom Pérignon Vintage", quantity: 1, unitPrice: 480, modifiers: [{ groupName: "Presentation", optionName: "Sparkler parade", priceDelta: 25 }] },
      { id: "oi-2", menuItemId: "mi-evian", name: "Evian 75cl", quantity: 2, unitPrice: 10, modifiers: [] },
    ],
    subtotal: 525,
    serviceFee: 26.25,
    tip: 50,
    total: 601.25,
    status: "pending",
    placedAt: minsAgo(3),
    updatedAt: minsAgo(3),
  },
  {
    id: "ord-2",
    code: "A-037",
    venueId: "venue-1",
    sessionId: "gs-4",
    tableId: "t-mf-1",
    tableCode: "MF-01",
    zoneId: "zone-dance",
    zoneName: "Main Floor",
    guestName: "Maxime",
    items: [
      { id: "oi-3", menuItemId: "mi-hendricks", name: "Hendrick's 1L", quantity: 1, unitPrice: 300, modifiers: [{ groupName: "Included washers", optionName: "Red Bull 4-pack", priceDelta: 24 }] },
    ],
    subtotal: 324,
    serviceFee: 16.2,
    tip: 32,
    total: 372.2,
    status: "accepted",
    placedAt: minsAgo(9),
    updatedAt: minsAgo(7),
  },
  {
    id: "ord-3",
    code: "A-036",
    venueId: "venue-1",
    tableId: "t-ter-1",
    tableCode: "TER-01",
    zoneId: "zone-terrace",
    zoneName: "Terrace",
    guestName: "Léa",
    items: [
      { id: "oi-4", menuItemId: "mi-patron", name: "Patrón Silver", quantity: 1, unitPrice: 320, modifiers: [{ groupName: "Included washers", optionName: "Orange juice carafe", priceDelta: 0 }] },
      { id: "oi-5", menuItemId: "mi-juice-carafe", name: "Fresh juice carafe", quantity: 2, unitPrice: 18, modifiers: [] },
    ],
    subtotal: 356,
    serviceFee: 17.8,
    tip: 40,
    total: 413.8,
    status: "preparing",
    placedAt: minsAgo(14),
    updatedAt: minsAgo(10),
  },
  {
    id: "ord-4",
    code: "A-035",
    venueId: "venue-1",
    sessionId: "gs-3",
    tableId: "t-vip-1",
    tableCode: "VIP-01",
    zoneId: "zone-vip",
    zoneName: "VIP Mezzanine",
    guestName: "Antoine",
    items: [
      { id: "oi-6", menuItemId: "mi-belvedere", name: "Belvedere Pure 1.75L", quantity: 1, unitPrice: 420, modifiers: [{ groupName: "Included washers", optionName: "Red Bull 4-pack", priceDelta: 24 }, { groupName: "Presentation", optionName: "LED sign + parade", priceDelta: 60 }] },
    ],
    subtotal: 504,
    serviceFee: 25.2,
    tip: 75,
    total: 604.2,
    status: "ready",
    placedAt: minsAgo(22),
    updatedAt: minsAgo(4),
  },
  {
    id: "ord-5",
    code: "A-034",
    venueId: "venue-1",
    sessionId: "gs-5",
    tableId: "t-bar-1",
    tableCode: "BAR-01",
    zoneId: "zone-bar",
    zoneName: "Back Bar",
    guestName: "Inès",
    items: [
      { id: "oi-7", menuItemId: "mi-diplomatico", name: "Diplomático Reserva Exclusiva", quantity: 1, unitPrice: 340, modifiers: [{ groupName: "Included washers", optionName: "Soda & tonic set", priceDelta: 0 }] },
      { id: "oi-8", menuItemId: "mi-soda-set", name: "Premium soda set", quantity: 1, unitPrice: 16, modifiers: [] },
    ],
    subtotal: 356,
    serviceFee: 17.8,
    tip: 35,
    total: 408.8,
    status: "delivered",
    placedAt: minsAgo(35),
    updatedAt: minsAgo(18),
  },
  {
    id: "ord-6",
    code: "A-033",
    venueId: "venue-1",
    tableId: "t-mf-5",
    tableCode: "MF-05",
    zoneId: "zone-dance",
    zoneName: "Main Floor",
    guestName: "Hugo",
    items: [
      { id: "oi-9", menuItemId: "mi-titos", name: "Tito's Handmade 1L", quantity: 1, unitPrice: 260, modifiers: [{ groupName: "Included washers", optionName: "Cranberry juice carafe", priceDelta: 0 }] },
    ],
    subtotal: 260,
    serviceFee: 13,
    tip: 0,
    total: 273,
    status: "delivered",
    placedAt: minsAgo(48),
    updatedAt: minsAgo(31),
  },
  {
    id: "ord-7",
    code: "A-032",
    venueId: "venue-1",
    tableId: "t-ter-5",
    tableCode: "TER-05",
    zoneId: "zone-terrace",
    zoneName: "Terrace",
    guestName: "Sarah",
    items: [
      { id: "oi-10", menuItemId: "mi-moet", name: "Moët & Chandon Impérial", quantity: 1, unitPrice: 260, modifiers: [] },
    ],
    subtotal: 260,
    serviceFee: 13,
    tip: 0,
    total: 273,
    status: "cancelled",
    placedAt: minsAgo(55),
    updatedAt: minsAgo(52),
  },
  {
    id: "ord-8",
    code: "A-031",
    venueId: "venue-1",
    sessionId: "gs-3",
    tableId: "t-vip-1",
    tableCode: "VIP-01",
    zoneId: "zone-vip",
    zoneName: "VIP Mezzanine",
    guestName: "Antoine",
    items: [
      { id: "oi-11", menuItemId: "mi-moet", name: "Moët & Chandon Impérial", quantity: 2, unitPrice: 260, modifiers: [] },
    ],
    subtotal: 520,
    serviceFee: 26,
    tip: 60,
    total: 606,
    status: "delivered",
    placedAt: minsAgo(20),
    updatedAt: minsAgo(12),
  },
];

export const mockGuestSessions: GuestSession[] = [
  { id: "gs-1", tableId: "t-mf-2", tableCode: "MF-02", zoneName: "Main Floor", displayName: "Julien + 3", partySize: 4, status: "pending", createdAt: minsAgo(2) },
  { id: "gs-2", tableId: "t-ter-3", tableCode: "TER-03", zoneName: "Terrace", displayName: "Camille + 5", partySize: 6, status: "pending", createdAt: minsAgo(5) },
  { id: "gs-3", tableId: "t-vip-1", tableCode: "VIP-01", zoneName: "VIP Mezzanine", displayName: "Antoine + 7", partySize: 8, status: "approved", createdAt: minsAgo(75) },
  { id: "gs-4", tableId: "t-mf-1", tableCode: "MF-01", zoneName: "Main Floor", displayName: "Maxime + 2", partySize: 3, status: "approved", createdAt: minsAgo(50) },
  { id: "gs-5", tableId: "t-bar-1", tableCode: "BAR-01", zoneName: "Back Bar", displayName: "Inès + 1", partySize: 2, status: "approved", createdAt: minsAgo(60) },
];

export const mockHelpRequests: HelpRequest[] = [
  { id: "hr-1", tableCode: "VIP-02", zoneName: "VIP Mezzanine", guestName: "Chloé", type: "refill-ice", status: "open", createdAt: minsAgo(4) },
  { id: "hr-2", tableCode: "MF-05", zoneName: "Main Floor", guestName: "Hugo", type: "call-waiter", status: "open", createdAt: minsAgo(7) },
  { id: "hr-3", tableCode: "TER-01", zoneName: "Terrace", guestName: "Léa", type: "clean-table", status: "acknowledged", createdAt: minsAgo(15) },
  { id: "hr-4", tableCode: "BAR-01", zoneName: "Back Bar", guestName: "Inès", type: "bill", status: "resolved", createdAt: minsAgo(25) },
];
