import type { Order, GuestSession, HelpRequest, ModifierKind, OrderItemModifier } from "@/lib/types";

const minsAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

function modifier(
  kind: ModifierKind,
  optionName: string,
  priceDelta: number,
  quantity = 1,
): OrderItemModifier {
  return {
    groupId: `mod-${kind}`,
    optionId: optionName.toLowerCase().replaceAll(" ", "-"),
    kind,
    groupName: kind === "washer" ? "Washers inclus" : "Présentation",
    optionName,
    priceDelta,
    quantity,
  };
}

export const mockOrders: Order[] = [
  {
    id: "ord-1",
    code: "A-038",
    venueId: "venue-1",
    tableId: "t-vip-2",
    tableCode: "VIP-02",
    zoneId: "zone-vip",
    zoneName: "VIP Mezzanine",
    guestName: "Chloé",
    items: [
      { id: "oi-1", menuItemId: "mi-dom", name: "Dom Pérignon Vintage", quantity: 1, unitPrice: 320, modifiers: [modifier("presentation", "Défilé de sparklers", 25)] },
      { id: "oi-2", menuItemId: "mi-evian", name: "Evian 75cl", quantity: 2, unitPrice: 8, modifiers: [] },
    ],
    subtotal: 361,
    serviceFee: 18.05,
    tip: 36,
    total: 415.05,
    status: "pending",
    placedAt: minsAgo(3),
    updatedAt: minsAgo(3),
  },
  {
    id: "ord-2",
    code: "A-037",
    venueId: "venue-1",
    sessionId: "gs-4",
    tableId: "t-mf-1",
    tableCode: "MF-01",
    zoneId: "zone-dance",
    zoneName: "Main Floor",
    guestName: "Maxime",
    items: [
      { id: "oi-3", menuItemId: "mi-hendricks", name: "Hendrick's 1L", quantity: 1, unitPrice: 210, modifiers: [modifier("washer", "Red Bull 4-pack", 24)] },
    ],
    subtotal: 234,
    serviceFee: 11.7,
    tip: 24,
    total: 269.7,
    status: "accepted",
    placedAt: minsAgo(9),
    updatedAt: minsAgo(7),
  },
  {
    id: "ord-3",
    code: "A-036",
    venueId: "venue-1",
    tableId: "t-ter-1",
    tableCode: "TER-01",
    zoneId: "zone-terrace",
    zoneName: "Terrace",
    guestName: "Léa",
    items: [
      { id: "oi-4", menuItemId: "mi-patron", name: "Patrón Silver", quantity: 1, unitPrice: 220, modifiers: [modifier("washer", "Carafe de jus d'orange", 0)] },
      { id: "oi-5", menuItemId: "mi-juice-carafe", name: "Carafe de jus frais", quantity: 2, unitPrice: 14, modifiers: [] },
    ],
    subtotal: 248,
    serviceFee: 12.4,
    tip: 25,
    total: 285.4,
    status: "preparing",
    placedAt: minsAgo(14),
    updatedAt: minsAgo(10),
  },
  {
    id: "ord-4",
    code: "A-035",
    venueId: "venue-1",
    sessionId: "gs-3",
    tableId: "t-vip-1",
    tableCode: "VIP-01",
    zoneId: "zone-vip",
    zoneName: "VIP Mezzanine",
    guestName: "Antoine",
    items: [
      { id: "oi-6", menuItemId: "mi-belvedere", name: "Belvedere Pure 1.75L", quantity: 1, unitPrice: 300, modifiers: [modifier("washer", "Red Bull 4-pack", 24), modifier("presentation", "Enseigne LED + défilé", 60)] },
    ],
    subtotal: 384,
    serviceFee: 19.2,
    tip: 50,
    total: 453.2,
    status: "ready",
    placedAt: minsAgo(22),
    updatedAt: minsAgo(4),
  },
  {
    id: "ord-5",
    code: "A-034",
    venueId: "venue-1",
    sessionId: "gs-5",
    tableId: "t-bar-1",
    tableCode: "BAR-01",
    zoneId: "zone-bar",
    zoneName: "Back Bar",
    guestName: "Inès",
    items: [
      { id: "oi-7", menuItemId: "mi-diplomatico", name: "Diplomático Reserva Exclusiva", quantity: 1, unitPrice: 240, modifiers: [modifier("washer", "Set soda & tonic", 0)] },
      { id: "oi-8", menuItemId: "mi-soda-set", name: "Set de sodas premium", quantity: 1, unitPrice: 12, modifiers: [] },
    ],
    subtotal: 252,
    serviceFee: 12.6,
    tip: 25,
    total: 289.6,
    status: "delivered",
    placedAt: minsAgo(35),
    updatedAt: minsAgo(18),
  },
  {
    id: "ord-6",
    code: "A-033",
    venueId: "venue-1",
    tableId: "t-mf-5",
    tableCode: "MF-05",
    zoneId: "zone-dance",
    zoneName: "Main Floor",
    guestName: "Hugo",
    items: [
      { id: "oi-9", menuItemId: "mi-titos", name: "Tito's Handmade 1L", quantity: 1, unitPrice: 180, modifiers: [modifier("washer", "Carafe de jus de canneberge", 0)] },
    ],
    subtotal: 180,
    serviceFee: 9,
    tip: 0,
    total: 189,
    status: "delivered",
    placedAt: minsAgo(48),
    updatedAt: minsAgo(31),
  },
  {
    id: "ord-7",
    code: "A-032",
    venueId: "venue-1",
    tableId: "t-ter-5",
    tableCode: "TER-05",
    zoneId: "zone-terrace",
    zoneName: "Terrace",
    guestName: "Sarah",
    items: [
      { id: "oi-10", menuItemId: "mi-moet", name: "Moët & Chandon Impérial", quantity: 1, unitPrice: 160, modifiers: [] },
    ],
    subtotal: 160,
    serviceFee: 8,
    tip: 0,
    total: 168,
    status: "cancelled",
    placedAt: minsAgo(55),
    updatedAt: minsAgo(52),
  },
  {
    id: "ord-8",
    code: "A-031",
    venueId: "venue-1",
    sessionId: "gs-3",
    tableId: "t-vip-1",
    tableCode: "VIP-01",
    zoneId: "zone-vip",
    zoneName: "VIP Mezzanine",
    guestName: "Antoine",
    items: [
      { id: "oi-11", menuItemId: "mi-moet", name: "Moët & Chandon Impérial", quantity: 2, unitPrice: 160, modifiers: [] },
    ],
    subtotal: 320,
    serviceFee: 16,
    tip: 40,
    total: 376,
    status: "delivered",
    placedAt: minsAgo(20),
    updatedAt: minsAgo(12),
  },
];

export const mockGuestSessions: GuestSession[] = [
  { id: "gs-1", tableId: "t-mf-2", tableCode: "MF-02", zoneName: "Main Floor", displayName: "Félix + 3", partySize: 4, status: "pending", createdAt: minsAgo(2) },
  { id: "gs-2", tableId: "t-ter-3", tableCode: "TER-03", zoneName: "Terrace", displayName: "Camille + 5", partySize: 6, status: "pending", createdAt: minsAgo(5) },
  { id: "gs-3", tableId: "t-vip-1", tableCode: "VIP-01", zoneName: "VIP Mezzanine", displayName: "Antoine + 7", partySize: 8, status: "approved", createdAt: minsAgo(75) },
  { id: "gs-4", tableId: "t-mf-1", tableCode: "MF-01", zoneName: "Main Floor", displayName: "Maxime + 2", partySize: 3, status: "approved", createdAt: minsAgo(50) },
  { id: "gs-5", tableId: "t-bar-1", tableCode: "BAR-01", zoneName: "Back Bar", displayName: "Inès + 1", partySize: 2, status: "approved", createdAt: minsAgo(60) },
];

export const mockHelpRequests: HelpRequest[] = [
  { id: "hr-1", sessionId: "gs-3", tableCode: "VIP-02", zoneName: "VIP Mezzanine", guestName: "Chloé", type: "refill-ice", status: "open", createdAt: minsAgo(4) },
  { id: "hr-2", sessionId: "gs-4", tableCode: "MF-05", zoneName: "Main Floor", guestName: "Hugo", type: "call-waiter", status: "open", createdAt: minsAgo(7) },
  { id: "hr-3", sessionId: "gs-5", tableCode: "TER-01", zoneName: "Terrace", guestName: "Léa", type: "clean-table", status: "acknowledged", createdAt: minsAgo(15) },
  { id: "hr-4", sessionId: "gs-5", tableCode: "BAR-01", zoneName: "Back Bar", guestName: "Inès", type: "bill", status: "resolved", createdAt: minsAgo(25) },
];
